//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public employee()
        {
            this.fac_attendence = new HashSet<fac_attendence>();
        }
    
        public string emp_id { get; set; }
        public string school_id { get; set; }
        public string emp_name { get; set; }
        public string emp_deg { get; set; }
        public decimal emp_exp { get; set; }
        public decimal emp_salary { get; set; }
        public string emp_address { get; set; }
        public decimal emp_age { get; set; }
        public string emp_sta { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fac_attendence> fac_attendence { get; set; }
        public virtual login login { get; set; }
        public virtual salary salary { get; set; }
        public virtual school school { get; set; }
    }
}
