//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee
    {
        public string stu_id { get; set; }
        public string class_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<int> is_paid { get; set; }
    
        public virtual myclass myclass { get; set; }
        public virtual student student { get; set; }
    }
}
