//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class login
    {
        public string id { get; set; }
        public string pwd { get; set; }
        public string role { get; set; }
        public string sta { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual employee employee { get; set; }
        public virtual student student { get; set; }
    }
}
