//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class mark
    {
        public string stu_id { get; set; }
        public string class_id { get; set; }
        public decimal out_of { get; set; }
        public decimal sub1 { get; set; }
        public decimal sub2 { get; set; }
        public decimal sub3 { get; set; }
        public decimal sub4 { get; set; }
        public decimal sub5 { get; set; }
        public int res { get; set; }
    
        public virtual myclass myclass { get; set; }
        public virtual student student { get; set; }
    }
}
