//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class ragistration
    {
        public string name { get; set; }
        public string con { get; set; }
        public string addre { get; set; }
        public string emailadd { get; set; }
        public string cla { get; set; }
        public string dob { get; set; }
        public string blood_gr { get; set; }
    }
}
