//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.stu_attendance = new HashSet<stu_attendance>();
        }
    
        public string stu_id { get; set; }
        public string school_id { get; set; }
        public string stu_name { get; set; }
        public string stu_class { get; set; }
        public string stu_address { get; set; }
        public string stu_dob { get; set; }
        public string stu_beh { get; set; }
        public string stu_con { get; set; }
        public string stu_blo_gr { get; set; }
        public string stu_sta { get; set; }
    
        public virtual fee fee { get; set; }
        public virtual login login { get; set; }
        public virtual mark mark { get; set; }
        public virtual myclass myclass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stu_attendance> stu_attendance { get; set; }
    }
}
