//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace school_management
{
    using System;
    using System.Collections.Generic;
    
    public partial class time_table
    {
        public string sub_id { get; set; }
        public string class_id { get; set; }
        public string period_id { get; set; }
    
        public virtual myclass myclass { get; set; }
        public virtual period period { get; set; }
        public virtual subject subject { get; set; }
    }
}
